### ISSUE TITLE
MVP suggestions

### ISSUE THREAD

**Issue by brtrick** [vincentahn/clamor#1]
MVPs are looking good! A couple suggestions:     
1. For the purposes of your FSP, I recommend just having a single Demo User that will automatically login with full functionality instead of setting up guest users. (On your sign in page, you can just have a button that will sign in Demo User.)     
2. The "Related to" fields are probably best discussed under your db schema. Focus on functionality and content here.
3. The list is pretty ambitious. Why don't you make the sixth MVP getting real-time messaging working and move the Voice Channel to a Bonus that you will complete if you have time. Getting the websockets to work  in real-time is worthy of its own MVP. :)

**Comment by vincentahn** [comment]
Thank you very much Brad! I've tried to address your suggestions:

1. I've changed the MVP List to contain a Demo User but I did have some concerns as to whether this would be okay because if multiple users try to use the same demo user then they can overwrite each other (as there is only one current session). 
2. I've removed the "related to" fields and attempted to address them in the db schema.
3. I've moved the voice channel to be a bonus and added real-time messaging as my 6th feature.

I've also updated the Private Message Feature to be read or update only because it will be a private channel between two users. If you think it may be better to homogenize text message channel and private message channel in some way please let me know.

Please let me know if you have any other suggestions and thank you very much for your review!

**Comment by brtrick** [comment]
Hi Vincent, 
Looks good. I know I said to make RT Messaging your sixth MVP, but it would probably make more sense to move it up to number 5 since you will want to get it working as part of your channel implementation. (And then it will be set up for your dms.)

Probably want to allow users to create a dm_channel as well (by sending the first message).

**Comment by brtrick** [comment]
Also, just to respond to your comments about the demo user, yes, you are correct, having a single demo user means that each person who logs in with that user can overwrite/change what someone else did as that user. But it is just a way for people (i.e., potential employers) to see your functionality without having to go through the trouble of creating an account.

**Comment by vincentahn** [comment]
Hi Brad!
-  I've switched RT Messaging and Private Messaging in the MVP order.
- I've added "Create" for Private Messaging but I'd like to explain why I previously didn't:
    - I didn't previously add create as a functionality because I didn't think I could state I was implementing "create" functionality if I don't make it such that the users manually create those channels
        - This is something I expect would be implemented if/when I try to implement private groups.
        - If/when I implement private groups I also expect to implement delete.
    - If your expectation was for me to definitely add private group messaging then I'll proceed with that in mind.
- I will try to revisit whether adding dm_channel by sending the first message works in the Front-end Routes issue as it might interfere with how I currently expected to retrieve information (retrieving most information from `GET /api/users` when user loads into "/channels/@me")
- My concern with the demo user wasn't so much that users could overwrite/change information but rather that there would be a clash between two demo users that were trying to access the site. I don't know if it should be considered an unlikely concern or not, but I imagine it would be frustrating for recruiter 1 to login while recruiter 2 is using the demo user only thereby forcing recruiter 2 back to the login page. It it's an unlikely concern I would like to continue with what's having demo user seeded in, but I hope to know your thoughts on this situation.

**Comment by brtrick** [comment]
Responding to your points:
1. Looks good! I'll close this issue with this comment.
2. You should definitely implement dms; group dms would be a bonus, but it wouldn't be that hard to expand the functionality. In terms of creating, the MVPs are about what your app does, not what the users do, so it would still be good to include it. I am curious as to how you are thinking of implementing the dms though. Are you automatically creating dm channels between every user? While that might work for the small scale of a clone, introducing any scale at all would quickly make that a major drag on your app.
3. Couple issues here. 1) It is a great idea to load a bunch of basic information into your state when a user logs in. Could you send that info back in the session response? Then you wouldn't need a separate route. 2) Again, loading all users in the app might work for the purposes of this clone, but it seems unnecessary and could create a performance drag with any scalability. What if you just load the users associated with the focused server?
4. Ah, ok, I understand. Probably not that likely that two people will login to the Demo User at one time, but you are correct, it could happen. This shouldn't cause one to logout, though. It just means that they might see things happening in their account that they are not doing. (It would like logging in simultaneously from two different browsers, which Discord allows.) You also might consider creating 2 Demo Users, which would make it easier for recruiters to experience your real-time messaging. You could also check and only allow a demo user login if the account is not online (or show if it is currently online / how many sessions it has open), but I would save that for a bonus.
