### ISSUE TITLE
Schema Suggestions

### ISSUE THREAD

**Issue by brtrick** [vincentahn/clamor#2]
Good job with the schema! A few suggestions:
1. Take another look at Discord's sign up modal. You will need to store a couple more fields for each user.
2. How will you track which members belong to each server?
3. Your text messages and dms are basically the same table. Unify those tables as messages.
4. Could also combine dm_chs and channels. Or you could keep them separate. Your choice, but it is worth thinking through the differences so you can explain why you chose the design you did. :)
5. You don't need separate fields for pics (profile, server). They will be handled through AWS and ActiveStorage.
6. Make table names plural
7. For each table with foreign keys, add bullet points to indicate the table that each foreign key references. (It would be good to add your has_many/belongs_to associations too.)
8. I'm not sure what you mean by "ensuring" certain fields. Could you clarify?

**Comment by brtrick** [comment]
Also, you probably want to ensure that channel names are unique within their server (but only within their server).

**Comment by vincentahn** [comment]
1. I'm assuming you're talking about email and date of birth. I was not planning on including those as they didn't seem to be functionally important but if you believe they should be included I will do so (and make username not unique).
2. That's a very big oversight on my part... I added user_ids as a column with an array of integers. Please let me know if you think more is required.
3. I have been struggling with this because I actually am not exactly certain of how to combine the two. Perhaps I could have a direct message channel be nested inside a "server" between two people? Otherwise I struggle to see how I can merge both messages and channels as they would be referencing different parents.
4. Same as question in 3rd point.
5. Understood. I will remove said fields.
6. Done.
7. Going to work on the last two tomorrow.

**Comment by brtrick** [comment]
1. Yes, you probably won't end up doing much with email and birthday, but you are trying to make a pixel perfect clone, and that is what Discord asks for, so... You can leave username as unique though, if you want.
2. Database can't really store an array of integers in a field. Think about a joins table instead.
3. There are several different ways to combine the messages and/or channels/dms. As you note, you could set up a server for dms. Alternatively, you could use a polymorphic association that would allow a message to attach to either a channel or a dm. As a third way, you could have a flag on your channel that indicates if it is private / a dm. Let me know if you want to talk through options!

**Comment by vincentahn** [comment]
Hi Brad,
I expect you'll read this after and by that time I hope everything is well.
- I have added email and birthday to users as suggested.
- I removed users being referenced to servers by founder_id directly as I figured that the user shouldn't directly need to know they found the server (only the founder should be able to delete the server but information regarding who is the founder will be saved within state when serverIndex calls for all servers). servers will still directly reference users through belongs_to.
- I tried to explain what "ensure" means for users. It just means that I plan on adding after_intialize methods that will ensure those fields are populated if they have not been input. In the case of session_token, the user should not have input on generating the session token so this is normal. In the case of profile picture, if the user does not insert a profile picture I will generate a random/default profile picture (just like Discord's with different background color logo).
- I have added server_memberships, private_memberships, and voice_channel_memberships as joint tables.
- I have finished adding all associations (I think).

**Comment by brtrick** [comment]
Well done. Storing founder_id under servers will definitely suffice as long as you only want to allow one owner. (And you are right, no need to store that info under user too.) Note that if you ever wanted to allow multiple people to "own" or "administer" a server, you could simply add a founder/admin boolean flag to the server_memberships joins table instead.

typeable seems an awkward name to me. Maybe consider "messageable"?

Closing this issue.

**Comment by vincentahn** [comment]
Added ui.modal to sample state.

**Comment by vincentahn** [comment]
Added ActiveStorage association for user, server, and private_channel.
