### ISSUE TITLE
Sample State suggestions

### ISSUE THREAD

**Issue by brtrick** [vincentahn/clamor#3]
Sample State looks good so far. Be sure to update to reflect any changes to the db schema.

**Comment by vincentahn** [comment]
I changed the state to better fit my purpose. I am expecting to retrieve a lot of information in the beginning and then configure the state to allow each higher level component to easily find information for its subcomponents. This is done by inserting an array of ids that will be included in the higher components to easily search for its relevant subcomponents. The hierarchy is as follows:

- servers
  - textChannels
    - messages
  - voiceChannels
- privateChannels
    - messages

Please let me know what you think!

**Comment by vincentahn** [comment]
I also added timestamp information to my sample state because I realized I probably need those for displaying when the message was written and edited.

**Comment by brtrick** [comment]
Looks good. You will need a way to associate users with private_channels though, either by having a slice of state for your private memberships or by using that table to store an array of user_ids under privateChannels. Same for servers / server memberships.

Also, I can envision scenarios (index?) where you would send up abbreviated user info, leaving off, e.g., the birthday.

**Comment by vincentahn** [comment]
You will need a way to associate users with private_channels... Same for servers / server memberships.
- Added user_ids array under both privateChannels and servers.

Also, I can envision scenarios (index?) where you would send up abbreviated user info, leaving off, e.g., the birthday.
- I don't quite understand this comment. First let me say that I currently understand Sample State to be talking about the state that is saved in store. If that understanding is incorrect please let me know. Considering that, I think if I want to send abbreviated user info (say current_user info) I can:
    - send a slice of state 
        - setup state props in a component such that only certain parts of current user information not related to birthday is sent (I know which user is current user because of session.currentUserId)
        - dispatch said information
- This is actually how `FieldForm` should work as it should only send one field and user input password at a time (Username and Password, Email and Password, New Password and Old Password).
- That said I'm not sure if that's what you meant by your comment. Could you elaborate further about what you mean by sending up abbreviated user info and the context?

**Comment by brtrick** [comment]
1. user_id arrays look good. Note that another way to solve that issue would be to set a slice of state for your joins table, but I personally like the arrays.
2. You are correct: sample state = store
3. Remember the Pokedex? For creating the index, the server only sent up basic information. When a user clicked on a pokemon's show page, the frontend requested that the server send up additional information: items, moves, details, etc. Birthday is something you probably don't need to load unless someone clicks on a show page. (Even then, does Discord show birthdays? i.e., would you ever need that info on the front-end for someone other than the current user?)

**Comment by vincentahn** [comment]
Remember the Pokedex? For creating the index, the server only sent up basic information. When a user clicked on a pokemon's show page, the frontend requested that the server send up additional information: items, moves, details, etc. Birthday is something you probably don't need to load unless someone clicks on a show page.
- This is a very good point. I should probably separate current user information (in session) and other user information (in users) anyway. I was also confused because I've always thought of server as higher than client so when I read "send up" I thought you wanted the client to send abbreviated information to the server. Thank you!

**Comment by vincentahn** [comment]
Changes:
- Sample State session now has more information about current user in session and less information about other users in users.

**Comment by brtrick** [comment]
You could still store the fuller information under users since it is user information. There is nothing wrong with some users in the store having more complete information than others.

**Comment by vincentahn** [comment]
I'll separate it for now but I'll keep that in mind if I run into issues in the future!
